language: scala

scala:
  - 2.12.6

script:
  - sbt test
  - sudo apt-get install -y bash zip
  - bash ./create-eb-bundle.sh

before_deploy:
  - sudo apt-get install -y python2.7 python-pip
  - sudo pip install awscli
  - bash ./create-eb-bundle.sh

deploy:
  - provider: script
    script:
      - bash ./publish-lambda.sh
    on:
      branch: master
    skip_cleanup: true
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "ap-southeast-1"
    app: "beeline-routing"
    bucket_name: "beeline-routing"
    zip_file: bundle.zip
    on:
      branch: master

