language: scala
services:
  - docker
scala:
  - 2.11.11

before_deploy:
  - bash ./create-eb-bundle.sh

deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "ap-southeast-1"
    app: "beeline-routing"
    env: "BeelineRouting-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-882000534153"
    zipfile: bundle.zip
    on:
      branch: master

